# Traefik-specific override configuration for demo.milou.sh
# This file configures services to work with Traefik reverse proxy instead of nginx

version: '3.8'

services:
  frontend:
    labels:
      - "traefik.enable=true"
      # Main frontend routing
      - "traefik.http.routers.milou-frontend.rule=Host(`demo.milou.sh`)"
      - "traefik.http.routers.milou-frontend.entrypoints=web,websecure"
      - "traefik.http.routers.milou-frontend.tls=true"
      - "traefik.http.routers.milou-frontend.tls.certresolver=myresolver"
      - "traefik.http.services.milou-frontend.loadbalancer.server.port=5173"
      - "traefik.docker.network=proxy"
      # Priority to ensure proper routing order (lowest priority = catch-all)
      - "traefik.http.routers.milou-frontend.priority=1"
      # HTTP to HTTPS redirect
      - "traefik.http.routers.milou-frontend-http.rule=Host(`demo.milou.sh`)"
      - "traefik.http.routers.milou-frontend-http.entrypoints=web"
      - "traefik.http.routers.milou-frontend-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      - milou_network
      - proxy

  backend:
    labels:
      - "traefik.enable=true"
      # API routing
      - "traefik.http.routers.milou-api.rule=Host(`demo.milou.sh`) && PathPrefix(`/api`)"
      - "traefik.http.routers.milou-api.entrypoints=web,websecure"
      - "traefik.http.routers.milou-api.tls=true"
      - "traefik.http.routers.milou-api.tls.certresolver=myresolver"
      - "traefik.http.routers.milou-api.service=milou-api"
      - "traefik.http.services.milou-api.loadbalancer.server.port=9999"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.milou-api.priority=100"
      # WebSocket routing for socket.io
      - "traefik.http.routers.milou-websocket.rule=Host(`demo.milou.sh`) && PathPrefix(`/socket.io`)"
      - "traefik.http.routers.milou-websocket.entrypoints=web,websecure"
      - "traefik.http.routers.milou-websocket.tls=true"
      - "traefik.http.routers.milou-websocket.tls.certresolver=myresolver"
      - "traefik.http.routers.milou-websocket.service=milou-websocket"
      - "traefik.http.services.milou-websocket.loadbalancer.server.port=9999"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.milou-websocket.priority=200"
    networks:
      - milou_network
      - proxy

  # Disable nginx when using Traefik
  nginx:
    deploy:
      replicas: 0

  # Ensure other services are on the correct networks if needed
  database:
    networks:
      - milou_network

  redis:
    networks:
      - milou_network

  rabbitmq:
    networks:
      - milou_network

  engine:
    networks:
      - milou_network

networks:
  proxy:
    external: true
  milou_network:
    driver: bridge